name: Publish Python 🐍 distributions 📦 to PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install setuptools, wheel and twine
        run : >-
          python -m
          pip install
          'setuptools<70' 'wheel<0.44' twine

      - name: Build a binary wheel and source directory
        run : >-
          python
          setup.py upload

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}